### ISSUE TITLE
Add ability to cherry pick branches for all repositories

### ISSUE THREAD

**Issue by hjr555** [i-e-b/LittleReviewer#6]
Default to master, but allow the tester to cherry pick other branches for other repositories.

This will allow testing when you have a dependency in another piece of code, that has not yet been merged into it's master branch.

**Comment by i-e-b** [comment]
This will probably mean a re-working of the UI entirely... which may not be a bad thing.
I will ponder on it.

**Comment by i-e-b** [comment]
Included in latest master
